### ISSUE TITLE
why the txt is 404

### ISSUE THREAD

**Issue by Wangddawei** [rtdi/S4HanaConnector#18]
Start Docker, the website can not be opened, error is one plug-in missing, 404
![image](https://user-images.githubusercontent.com/52993046/109947882-c271fc00-7d14-11eb-9882-fd19b6df3bf0.png)

**Comment by Wangddawei** [comment]
what should i do?

**Comment by wernerdaehn** [comment]
I thought I fixed it. Let me check.

**Comment by wernerdaehn** [comment]
It is a version dependency issue tomcat9, tomcat10

**Comment by Wangddawei** [comment]
> It is a version dependency issue tomcat9, tomcat10

Thanks for your reply,  the tomcat environment is in this docker image, how can I change it?

**Comment by Wangddawei** [comment]
> It is a version dependency issue tomcat9, tomcat10

Thanks for your reply,  the tomcat environment is in this docker image, how can I change the tomcat version?

**Comment by wernerdaehn** [comment]
May I ask for 12 hours of time, then I can try it myself and fix it.

**Comment by Wangddawei** [comment]
> May I ask for 12 hours of time, then I can try it myself and fix it.
ok ,Thank you for your reply，I'm waiting for your answer.

**Comment by DmitryTaliuk** [comment]
Hi, I have same issue.
`docker container logs s4hanaconnector` command shows next error:

**Comment by wernerdaehn** [comment]
But that log looks correct. If you can see the home screen of the connector, then the first step is to create a connection to your Kafka server. That's what that error says.

**Comment by DmitryTaliuk** [comment]
I can see only blank screen like @Wangddawei in the start of topic

**Comment by wernerdaehn** [comment]
ok, let me check.

**Comment by wernerdaehn** [comment]
One thing I can tell immediately: It is the root page for all apps installed that has a problem. The connector is fine.
Hence please open the URL including the webapp name, e.g. http://localhost/s4hanaconnector instead of http://localhost
The other point I will check later.

**Comment by wernerdaehn** [comment]
Fixed.
Details in case you want to know: Each connector is a web application, hence the URL must contain it. But as users might not know the URL I wrote a [ConnectorRootApp](https://github.com/rtdi/ConnectorRootApp) which is an app that belongs to the root url and does analyse all installed web applications and shows those.

This ConnectorRootApp is used in all connectors, hence must be tomcat10 based. But it is used for the HanaAppContainer as well, this is using the OLingo library which does not work with tomcat9. So I created one docker image for tomcat9 and one for tomcat10. The tomcat10 I forgot to merge master->main hence it was a tomcat10 web server running a tomcat9 compiled ConnectorRootApp. And this is not supported due to the javax -> jakarta package rename.
But it affected only the root web application, the s4hanaconnector web application was fine the entire time.

Please confirm and close.

**Comment by Wangddawei** [comment]
Thanks，The web page is now open normally.
