### ISSUE TITLE
Topic cannot be read

### ISSUE THREAD

**Issue by 13639577519** [rtdi/S4HanaConnector#19]
Hello, I'm sorry to take up your valuable time. I encountered a problem when configuring the parameters of Kafka on the web page. The alicloud version of Kafka does not provide the parameter configuration of optional schema registry, so can I not fill in the parameters of optional schema registry? When I try not to configure the optional schema registry parameter, an error of topic cannot be read will appear in the save step. Is there any solution? Looking forward to your reply, thank you very much
![image](https://user-images.githubusercontent.com/53895233/110076726-edfdf080-7dbf-11eb-8dc4-56bc9e9fcf5b.png)

**Comment by 13639577519** [comment]
![image](https://user-images.githubusercontent.com/53895233/110076932-42a16b80-7dc0-11eb-825b-9733b1c5d8f6.png)

**Comment by wernerdaehn** [comment]
Yes, these parameters are optional, but...

As the solution is using Avro to achieve all of its advantages, some sort of schema registration is required. If no URL is provided, then a new topic _schema is created automatically that simulates the schema registry. So it should work. Not sure why the error is "Topic cannot be read" instead of cannot be created but I suspect same issue in that area. Permissions or something else. Anyway, we will find out together.

On the top right of the screen should be an error button where you can browse into the details, down to the Java stack trace. That would be interesting to see. And I check the code (and change it so the error prints the topic name it cannot read from).

**Comment by 13639577519** [comment]
Thank you very much for your reply. At the same time, according to your method of finding exceptions, I found this place in the code. Can I find the specific cause of the error according to this content?

![image](https://user-images.githubusercontent.com/53895233/110080072-f3116e80-7dc4-11eb-8441-87f41d13cc9f.png)

**Comment by wernerdaehn** [comment]
Yes, this would be shown when you press that button on the top right. Is it highlighted and has the number of errors?

**Comment by 13639577519** [comment]
Yes, there will be an error number

![image](https://user-images.githubusercontent.com/53895233/110080788-f0fbdf80-7dc5-11eb-9a3c-10f6918d905f.png)

**Comment by 13639577519** [comment]
![Uploading image.png…]()

**Comment by 13639577519** [comment]
![image](https://user-images.githubusercontent.com/53895233/110081009-40421000-7dc6-11eb-8585-cf27ef388bb4.png)

**Comment by wernerdaehn** [comment]
And now open one of the errors for the details....

**Comment by 13639577519** [comment]
The Java code screenshot just now is drilled down here

![image](https://user-images.githubusercontent.com/53895233/110081244-9a42d580-7dc6-11eb-8026-a4bf3c2b0c2c.png)
![image](https://user-images.githubusercontent.com/53895233/110081282-a9298800-7dc6-11eb-99f4-d331fbb67d79.png)
![image](https://user-images.githubusercontent.com/53895233/110081300-b2b2f000-7dc6-11eb-8dc3-81eb2603a8df.png)

**Comment by wernerdaehn** [comment]
As you see, the _schemas topic cannot be read. It cannot be read because the connector was not able to create it. That can have multiple reasons, permissions but also the Kafka Server version you are using. It must be a rather current one as I am using the defaults for partitioning when creating a topic but that was added a year ago into Kafka server.

There are a couple of topics that need to be created, _schemas, the topic storing the transactions, impact/lineage metadata etc.

Not sure how to proceed.

**Comment by 13639577519** [comment]
OK, I see. I'm trying to find out the reason and see if I can find it. I also want to ask you a question. Besides Kafka connect and s4hanaconnector, do you have any suggestions for collecting data from SAP Hana and sending it to Kafka?

**Comment by wernerdaehn** [comment]
I would differentiate here between technologies/APIs and products.
SAP provides only so much APIs or approaches to get data from Hana and S/4Hana. In the context of Kafka I assume we talk about realtime, hence I limit the answer to these.
The only possible option in Hana are triggers. In S/4 Hana something can be done in the ABAP layer as well, e.g. IDOCs.
From the not-supported options Hana has a transaction log which is a file and if you know the structure, you know what has been changed.

Triggers are used by SAP SLT, by my HanaConnector and S/4HanaConnector.
Transaction log reading is done by [HVR Software](https://www.hvr-software.com/solutions/database-replication/). 

On application level the ODP/ODQ ABAP interface is the standard and this API can be fed with change data by SLT, BW and BWExtractors. This is another connector I am building at the moment, [Init Software](https://www.confluent.io/hub/init/kafka-connect-odp) has one already.

Please note that none of the solutions are perfect. HVR for example can load Kafka but needs a shadow database also. Such kinds of surprises are common to all approaches because all share the same problem including SAP SLT: The SAP kernels do not provide a generic CDC method.

**Comment by 13639577519** [comment]
OK, thank you very much for your point of view, which is very useful to me. I will try it. Thank you again. At the same time, I hope to see another connector you developed earlier. I wish you success
